// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoCodeGenerationVSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "AutoCodeGenerationVSIX.c00b7b96-9eb7-4ed2-a8d2-4c9d9f67e018";
        public const string Name = "AutoCodeGeneration";
        public const string Description = @"This extension provides auto code generation for simple architecture in .NET 8 projects, including DTOs, context updates, abstract classes, Entity Framework, and interfaces implementations.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "legolasgfb431907@outlook.com";
        public const string Tags = "code generation, .NET, simple architecture, .Net Core";
    }
}
